-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 19:51:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movesmart
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movesmart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movesmart` DEFAULT CHARACTER SET utf8 ;
USE `movesmart` ;

-- -----------------------------------------------------
-- Table `movesmart`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movesmart`.`Usuario` (
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movesmart`.`OD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movesmart`.`OD` (
  `id_od` INT NOT NULL,
  `horario` TIME NULL,
  `origem` VARCHAR(45) NULL,
  `destino` VARCHAR(45) NULL,
  `Usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_od`, `Usuario_id_usuario`),
  INDEX `fk_OD_Usuario1_idx` (`Usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_id_OD`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `movesmart`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movesmart`.`Onibus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movesmart`.`Onibus` (
  `id_onibus` INT NOT NULL,
  `numero` VARCHAR(45) NULL,
  PRIMARY KEY (`id_onibus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movesmart`.`Rota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movesmart`.`Rota` (
  `id_rota` INT NOT NULL,
  `Onibus_id_onibus` INT NOT NULL,
  PRIMARY KEY (`id_rota`, `Onibus_id_onibus`),
  INDEX `fk_Rota_Onibus1_idx` (`Onibus_id_onibus` ASC) VISIBLE,
  CONSTRAINT `fk_Onibus_id_Rota`
    FOREIGN KEY (`Onibus_id_onibus`)
    REFERENCES `movesmart`.`Onibus` (`id_onibus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movesmart`.`Ponto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movesmart`.`Ponto` (
  `id_ponto` INT NOT NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero` INT NULL,
  `Rota_id_rota` INT NOT NULL,
  `OD_id_od` INT NOT NULL,
  PRIMARY KEY (`id_ponto`, `Rota_id_rota`, `OD_id_od`),
  INDEX `fk_Pontos_Rota1_idx` (`Rota_id_rota` ASC) VISIBLE,
  INDEX `fk_Pontos_OD1_idx` (`OD_id_od` ASC) VISIBLE,
  CONSTRAINT `fk_Rota_id_Ponto`
    FOREIGN KEY (`Rota_id_rota`)
    REFERENCES `movesmart`.`Rota` (`id_rota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OD_id_Ponto`
    FOREIGN KEY (`OD_id_od`)
    REFERENCES `movesmart`.`OD` (`id_od`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movesmart`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movesmart`.`Horario` (
  `id_horario` INT NOT NULL,
  `horario` TIME NULL,
  `Onibus_id_onibus` INT NOT NULL,
  PRIMARY KEY (`id_horario`, `Onibus_id_onibus`),
  INDEX `fk_Horario_Onibus1_idx` (`Onibus_id_onibus` ASC) VISIBLE,
  CONSTRAINT `fk_Onibus_id_Horario`
    FOREIGN KEY (`Onibus_id_onibus`)
    REFERENCES `movesmart`.`Onibus` (`id_onibus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movesmart`.`Onibus_has_Ponto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movesmart`.`Onibus_has_Ponto` (
  `Onibus_id_onibus` INT NOT NULL,
  `Pontos_id_pontos` INT NOT NULL,
  `Pontos_Rota_id_rota` INT NOT NULL,
  `Pontos_OD_id_od` INT NOT NULL,
  PRIMARY KEY (`Onibus_id_onibus`, `Pontos_id_pontos`, `Pontos_Rota_id_rota`, `Pontos_OD_id_od`),
  INDEX `fk_Onibus_has_Pontos_Pontos1_idx` (`Pontos_id_pontos` ASC, `Pontos_Rota_id_rota` ASC, `Pontos_OD_id_od` ASC) VISIBLE,
  INDEX `fk_Onibus_has_Pontos_Onibus1_idx` (`Onibus_id_onibus` ASC) VISIBLE,
  CONSTRAINT `fk_Onibus_id_Onibus_has_Ponto`
    FOREIGN KEY (`Onibus_id_onibus`)
    REFERENCES `movesmart`.`Onibus` (`id_onibus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ponto_id_Onibus_has_Ponto`
    FOREIGN KEY (`Pontos_id_pontos` , `Pontos_Rota_id_rota` , `Pontos_OD_id_od`)
    REFERENCES `movesmart`.`Ponto` (`id_ponto` , `Rota_id_rota` , `OD_id_od`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
